import { ApiProperty } from '@nestjs/swagger';

export class RecordEngagementDto {
  @ApiProperty({ required: false, description: 'Total likes the post received.' })
  likes?: number;

  @ApiProperty({ required: false, description: 'Total comments generated by the content.' })
  comments?: number;

  @ApiProperty({ required: false, description: 'Number of shares or reposts.' })
  shares?: number;

  @ApiProperty({ required: false, description: 'Saves or bookmarks captured for the content.' })
  saves?: number;

  @ApiProperty({ required: false, description: 'Impressions recorded for the post.' })
  impressions?: number;

  @ApiProperty({ required: false, description: 'Reach or unique viewers exposed to the post.' })
  reach?: number;

  @ApiProperty({ required: false, description: 'Outbound link clicks generated.' })
  clicks?: number;
}
